<a href="https://colab.research.google.com/github/jhamidi1/Data-205-Capstone-Project/blob/main/DATA%20205%20Capstone%20Project%20Code/01_DATA205_Data_Cleaning_and_Merging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Ingestion

This notebook loads, cleans, and merges neighborhood level datasets related to education, income, and poverty.

In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving 01_Educational_Attainment.csv to 01_Educational_Attainment.csv
Saving 02_Aggregate_Household_Income.csv to 02_Aggregate_Household_Income.csv
Saving 03_Poverty_Status.csv to 03_Poverty_Status.csv

In [4]:
education = pd.read_csv("01_Educational_Attainment.csv")

income = pd.read_csv("02_Aggregate_Household_Income.csv")

poverty = pd.read_csv("03_Poverty_Status.csv")

In [5]:
education.head()
income.head()
poverty.head()

,Neighborhood,Id,Estimate; Total:,Margin of Error; Total:,Estimate; Income in the past 12 months below poverty level:,Margin of Error; Income in the past 12 months below poverty level:,Estimate; Income in the past 12 months below poverty level: - In family households:,Margin of Error; Income in the past 12 months below poverty level: - In family households:,Estimate; Income in the past 12 months below poverty level: - In family households: - In married couple families:,Margin of Error; Income in the past 12 months below poverty level: - In family households: - In married couple families:,...,Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement:,Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement:,Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder:,Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder:,Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder: - Living alone,Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder: - Living alone,Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder: - Not living alone,Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder: - Not living alone,Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Other living arrangement,Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Other living arrangement
0,Allegheny Center,1,1130.0,184.000000,516.0,195.000000,290.0,202.000000,163.0,195.000000,...,471.0,113.000000,375.0,85.000000,309.0,80.000000,66.0,38.000000,96.0,57.000000
1,Allegheny West,2,331.0,104.000000,45.0,26.000000,0.0,10.000000,0.0,10.000000,...,87.0,40.000000,79.0,36.000000,66.0,34.000000,13.0,13.000000,8.0,11.000000
2,Allentown,3,2624.0,499.013026,750.0,397.315995,490.0,400.251171,0.0,17.320508,...,394.0,136.638208,328.0,105.877287,274.0,98.208961,54.0,54.083269,66.0,56.964901
3,Arlington,4,1890.0,367.887211,343.0,160.626897,279.0,158.776573,97.0,96.046864,...,434.0,172.565929,230.0,71.679844,125.0,51.855569,105.0,49.608467,204.0,117.635029
4,Arlington Heights,5,380.0,196.000000,278.0,198.000000,257.0,196.000000,0.0,10.000000,...,47.0,38.000000,47.0,38.000000,47.0,38.000000,0.0,10.000000,0.0,10.000000

In [6]:
education.columns = education.columns.str.strip()
income.columns = income.columns.str.strip()
poverty.columns = poverty.columns.str.strip()

In [7]:
print(education.columns)
print(income.columns)
print(poverty.columns)

Index(['Neighborhood', 'Id', 'Estimate; Total:', 'Margin of Error; Total:',
       'Estimate; Male:', 'Margin of Error; Male:',
       'Estimate; Male: - No schooling completed',
       'Margin of Error; Male: - No schooling completed',
       'Estimate; Male: - Nursery to 4th grade',
       'Margin of Error; Male: - Nursery to 4th grade',
       'Estimate; Male: - 5th and 6th grade',
       'Margin of Error; Male: - 5th and 6th grade',
       'Estimate; Male: - 7th and 8th grade',
       'Margin of Error; Male: - 7th and 8th grade',
       'Estimate; Male: - 9th grade', 'Margin of Error; Male: - 9th grade',
       'Estimate; Male: - 10th grade', 'Margin of Error; Male: - 10th grade',
       'Estimate; Male: - 11th grade', 'Margin of Error; Male: - 11th grade',
       'Estimate; Male: - 12th grade, no diploma',
       'Margin of Error; Male: - 12th grade, no diploma',
       'Estimate; Male: - High school graduate (includes equivalency)',
       'Margin of Error; Male: - High school graduate (includes equivalency)',
       'Estimate; Male: - Some college, less than 1 year',
       'Margin of Error; Male: - Some college, less than 1 year',
       'Estimate; Male: - Some college, 1 or more years, no degree',
       'Margin of Error; Male: - Some college, 1 or more years, no degree',
       'Estimate; Male: - Associate's degree',
       'Margin of Error; Male: - Associate's degree',
       'Estimate; Male: - Bachelor's degree',
       'Margin of Error; Male: - Bachelor's degree',
       'Estimate; Male: - Master's degree',
       'Margin of Error; Male: - Master's degree',
       'Estimate; Male: - Professional school degree',
       'Margin of Error; Male: - Professional school degree',
       'Estimate; Male: - Doctorate degree',
       'Margin of Error; Male: - Doctorate degree', 'Estimate; Female:',
       'Margin of Error; Female:',
       'Estimate; Female: - No schooling completed',
       'Margin of Error; Female: - No schooling completed',
       'Estimate; Female: - Nursery to 4th grade',
       'Margin of Error; Female: - Nursery to 4th grade',
       'Estimate; Female: - 5th and 6th grade',
       'Margin of Error; Female: - 5th and 6th grade',
       'Estimate; Female: - 7th and 8th grade',
       'Margin of Error; Female: - 7th and 8th grade',
       'Estimate; Female: - 9th grade', 'Margin of Error; Female: - 9th grade',
       'Estimate; Female: - 10th grade',
       'Margin of Error; Female: - 10th grade',
       'Estimate; Female: - 11th grade',
       'Margin of Error; Female: - 11th grade',
       'Estimate; Female: - 12th grade, no diploma',
       'Margin of Error; Female: - 12th grade, no diploma',
       'Estimate; Female: - High school graduate (includes equivalency)',
       'Margin of Error; Female: - High school graduate (includes equivalency)',
       'Estimate; Female: - Some college, less than 1 year',
       'Margin of Error; Female: - Some college, less than 1 year',
       'Estimate; Female: - Some college, 1 or more years, no degree',
       'Margin of Error; Female: - Some college, 1 or more years, no degree',
       'Estimate; Female: - Associate's degree',
       'Margin of Error; Female: - Associate's degree',
       'Estimate; Female: - Bachelor's degree',
       'Margin of Error; Female: - Bachelor's degree',
       'Estimate; Female: - Master's degree',
       'Margin of Error; Female: - Master's degree',
       'Estimate; Female: - Professional school degree',
       'Margin of Error; Female: - Professional school degree',
       'Estimate; Female: - Doctorate degree',
       'Margin of Error; Female: - Doctorate degree'],
      dtype='object')
Index(['Neighborhood', 'Id', 'Estimate; Total:', 'Margin of Error; Total:',
       'Estimate; Total: - With wage or salary income',
       'Margin of Error; Total: - With wage or salary income',
       'Estimate; Total: - No wage or salary income',
       'Margin of Error; Total: - No wage or salary income'],
      dtype='object')
Index(['Neighborhood', 'Id', 'Estimate; Total:', 'Margin of Error; Total:',
       'Estimate; Income in the past 12 months below poverty level:',
       'Margin of Error; Income in the past 12 months below poverty level:',
       'Estimate; Income in the past 12 months below poverty level: - In family households:',
       'Margin of Error; Income in the past 12 months below poverty level: - In family households:',
       'Estimate; Income in the past 12 months below poverty level: - In family households: - In married couple families:',
       'Margin of Error; Income in the past 12 months below poverty level: - In family households: - In married couple families:',
       'Estimate; Income in the past 12 months below poverty level: - In family households: - In married couple families: - All relatives',
       'Margin of Error; Income in the past 12 months below poverty level: - In family households: - In married couple families: - All relatives',
       'Estimate; Income in the past 12 months below poverty level: - In family households: - In married couple families: - Non-relatives',
       'Margin of Error; Income in the past 12 months below poverty level: - In family households: - In married couple families: - Non-relatives',
       'Estimate; Income in the past 12 months below poverty level: - In family households: - In other families:',
       'Margin of Error; Income in the past 12 months below poverty level: - In family households: - In other families:',
       'Estimate; Income in the past 12 months below poverty level: - In family households: - In other families: - Male householder, no wife present:',
       'Margin of Error; Income in the past 12 months below poverty level: - In family households: - In other families: - Male householder, no wife present:',
       'Estimate; Income in the past 12 months below poverty level: - In family households: - In other families: - Male householder, no wife present: - All relatives',
       'Margin of Error; Income in the past 12 months below poverty level: - In family households: - In other families: - Male householder, no wife present: - All relatives',
       'Estimate; Income in the past 12 months below poverty level: - In family households: - In other families: - Male householder, no wife present: - Non-relatives',
       'Margin of Error; Income in the past 12 months below poverty level: - In family households: - In other families: - Male householder, no wife present: - Non-relatives',
       'Estimate; Income in the past 12 months below poverty level: - In family households: - In other families: - Female householder, no husband present:',
       'Margin of Error; Income in the past 12 months below poverty level: - In family households: - In other families: - Female householder, no husband present:',
       'Estimate; Income in the past 12 months below poverty level: - In family households: - In other families: - Female householder, no husband present: - All relatives',
       'Margin of Error; Income in the past 12 months below poverty level: - In family households: - In other families: - Female householder, no husband present: - All relatives',
       'Estimate; Income in the past 12 months below poverty level: - In family households: - In other families: - Female householder, no husband present: - Non-relatives',
       'Margin of Error; Income in the past 12 months below poverty level: - In family households: - In other families: - Female householder, no husband present: - Non-relatives',
       'Estimate; Income in the past 12 months below poverty level: - In non-family households and other living arrangement:',
       'Margin of Error; Income in the past 12 months below poverty level: - In non-family households and other living arrangement:',
       'Estimate; Income in the past 12 months below poverty level: - In non-family households and other living arrangement: - Householder:',
       'Margin of Error; Income in the past 12 months below poverty level: - In non-family households and other living arrangement: - Householder:',
       'Estimate; Income in the past 12 months below poverty level: - In non-family households and other living arrangement: - Householder: - Living alone',
       'Margin of Error; Income in the past 12 months below poverty level: - In non-family households and other living arrangement: - Householder: - Living alone',
       'Estimate; Income in the past 12 months below poverty level: - In non-family households and other living arrangement: - Householder: - Not living alone',
       'Margin of Error; Income in the past 12 months below poverty level: - In non-family households and other living arrangement: - Householder: - Not living alone',
       'Estimate; Income in the past 12 months below poverty level: - In non-family households and other living arrangement: - Other living arrangement',
       'Margin of Error; Income in the past 12 months below poverty level: - In non-family households and other living arrangement: - Other living arrangement',
       'Estimate; Income in the past 12 months at or above poverty level:',
       'Margin of Error; Income in the past 12 months at or above poverty level:',
       'Estimate; Income in the past 12 months at or above poverty level: - In family households:',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In family households:',
       'Estimate; Income in the past 12 months at or above poverty level: - In family households: - In married couple families:',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In family households: - In married couple families:',
       'Estimate; Income in the past 12 months at or above poverty level: - In family households: - In married couple families: - All relatives',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In family households: - In married couple families: - All relatives',
       'Estimate; Income in the past 12 months at or above poverty level: - In family households: - In married couple families: - Non-relatives',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In family households: - In married couple families: - Non-relatives',
       'Estimate; Income in the past 12 months at or above poverty level: - In family households: - In other families:',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In family households: - In other families:',
       'Estimate; Income in the past 12 months at or above poverty level: - In family households: - In other families: - Male householder, no wife present:',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In family households: - In other families: - Male householder, no wife present:',
       'Estimate; Income in the past 12 months at or above poverty level: - In family households: - In other families: - Male householder, no wife present: - All relatives',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In family households: - In other families: - Male householder, no wife present: - All relatives',
       'Estimate; Income in the past 12 months at or above poverty level: - In family households: - In other families: - Male householder, no wife present: - Non-relatives',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In family households: - In other families: - Male householder, no wife present: - Non-relatives',
       'Estimate; Income in the past 12 months at or above poverty level: - In family households: - In other families: - Female householder, no husband present:',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In family households: - In other families: - Female householder, no husband present:',
       'Estimate; Income in the past 12 months at or above poverty level: - In family households: - In other families: - Female householder, no husband present: - All relatives',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In family households: - In other families: - Female householder, no husband present: - All relatives',
       'Estimate; Income in the past 12 months at or above poverty level: - In family households: - In other families: - Female householder, no husband present: - Non-relatives',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In family households: - In other families: - Female householder, no husband present: - Non-relatives',
       'Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement:',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement:',
       'Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder:',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder:',
       'Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder: - Living alone',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder: - Living alone',
       'Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder: - Not living alone',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Householder: - Not living alone',
       'Estimate; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Other living arrangement',
       'Margin of Error; Income in the past 12 months at or above poverty level: - In non-family households and other living arrangement: - Other living arrangement'],
      dtype='object')

In [8]:
merged = education.merge(income, on="Neighborhood", how="inner")
merged = merged.merge(poverty, on="Neighborhood", how="inner")

In [9]:
# Create a cleaner final dataset with only the variables needed for analysis

final_data = merged[[
    "Neighborhood",
    "Estimate; Total:_x",
    "Estimate; Male: - Bachelor's degree",
    "Estimate; Female: - Bachelor's degree",
    "Estimate; Total: - With wage or salary income",
    "Estimate; Total:_y",
    "Estimate; Income in the past 12 months below poverty level:"
]].copy()

# Rename the columns to simpler names
final_data = final_data.rename(columns={
    "Estimate; Total:_x": "Adult_Population_25_Over",
    "Estimate; Male: - Bachelor's degree": "Male_Bachelors_Degree",
    "Estimate; Female: - Bachelor's degree": "Female_Bachelors_Degree",
    "Estimate; Total: - With wage or salary income": "Households_With_Wage_Income",
    "Estimate; Total:_y": "Total_Households",
    "Estimate; Income in the past 12 months below poverty level:": "Population_Below_Poverty"
})

# Create the calculated variables
final_data["Total_Bachelors_Degree"] = (
    final_data["Male_Bachelors_Degree"] + final_data["Female_Bachelors_Degree"]
)

final_data["Bachelors_Degree_Pct"] = (
    final_data["Total_Bachelors_Degree"] / final_data["Adult_Population_25_Over"] * 100
)

final_data["Wage_Income_Pct"] = (
    final_data["Households_With_Wage_Income"] / final_data["Total_Households"] * 100
)

final_data["Poverty_Rate"] = (
    final_data["Population_Below_Poverty"] /
    (final_data["Population_Below_Poverty"] + merged["Estimate; Income in the past 12 months at or above poverty level:"])
    * 100
)

# Keep final columns
final_data = final_data[[
    "Neighborhood",
    "Adult_Population_25_Over",
    "Total_Bachelors_Degree",
    "Bachelors_Degree_Pct",
    "Total_Households",
    "Households_With_Wage_Income",
    "Wage_Income_Pct",
    "Population_Below_Poverty",
    "Poverty_Rate"
]]

# Round percentage columns
final_data["Bachelors_Degree_Pct"] = final_data["Bachelors_Degree_Pct"].round(2)
final_data["Wage_Income_Pct"] = final_data["Wage_Income_Pct"].round(2)
final_data["Poverty_Rate"] = final_data["Poverty_Rate"].round(2)

# Preview final cleaned data
final_data.head()

,Neighborhood,Adult_Population_25_Over,Total_Bachelors_Degree,Bachelors_Degree_Pct,Total_Households,Households_With_Wage_Income,Wage_Income_Pct,Population_Below_Poverty,Poverty_Rate
0,Allegheny Center,791.0,176.0,22.25,733.0,462.0,63.03,516.0,45.66
1,Allegheny West,283.0,121.0,42.76,150.0,120.0,80.00,45.0,13.60
2,Allentown,1611.0,72.0,4.47,1138.0,772.0,67.84,750.0,28.58
3,Arlington,1271.0,84.0,6.61,685.0,566.0,82.63,343.0,18.15
4,Arlington Heights,182.0,0.0,0.00,170.0,96.0,56.47,278.0,73.16

In [16]:
final_data.to_csv("04_Final_Merged_Pittsburgh_Neighborhood_Data.csv", index=False)

from google.colab import files
files.download("04_Final_Merged_Pittsburgh_Neighborhood_Data.csv")